services:
  - type: web
    name: mesa-cambio
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APP_USER
        sync: false
      - key: APP_PASSWORD
        sync: false
